//! Memory→entity mention linking + provenance descriptions (#24).
//!
//! Spectral's `remember_with` never links a memory to the entities it talks
//! about — only `ingest_document` runs the Canonicalizer, and runtime-created
//! entities (people/projects) aren't in the ontology at all. The result the owner
//! saw: "New Brunswick" and "Mel Schembri" nodes with 0 memories and no
//! description. This module closes that gap on our side of the pin:
//!
//! * `backfill_memory_mentions` — one idempotent pass over every stored
//!   memory, matching graph-entity canonical names in the text and writing
//!   `document` + `mention` rows (the same tables `ingest_document` uses).
//! * `link_new_memory` — the real-time path, called from
//!   [`SafeBrain::remember_with`](crate::brain_handle::SafeBrain::remember_with)
//!   after every successful write so the graph grows as the user works.
//! * Provenance descriptions — entities whose freeform description is empty
//!   get an honest auto-note: what kind of thing it is, how many memories
//!   mention it, since when, and the first snippet. Curated / LLM-enriched
//!   descriptions are never clobbered (the update matches only empty or
//!   auto-generated text).
//!
//! Direct SQL against `graph.sqlite` follows the established bridge pattern
//! in [`crate::project_graph`] (the pinned spectral API has no list/query
//! surface for this). Synchronous rusqlite — call from `spawn_blocking`.

use std::collections::HashMap;
use std::path::Path;

/// Signature substring that marks a description as auto-generated by this
/// module. The refresh UPDATE only overwrites empty descriptions or ones
/// containing this marker, so human/LLM text always wins.
const AUTO_NOTE_MARKER: &str = "the brain tracks — mentioned in";

/// Minimum canonical-name length eligible for text matching. Shorter names
/// ("ai", "ui") false-positive far more than they link.
const MIN_ALIAS_LEN: usize = 3;

#[derive(Debug, Clone)]
pub struct EntityAlias {
    pub id: Vec<u8>,
    pub hex: String,
    pub entity_type: String,
    /// Already `graph_canonical`-normalized (lowercase, collapsed whitespace).
    pub canonical: String,
}

#[derive(Debug, Clone)]
pub struct LinkedEntity {
    pub hex: String,
    pub entity_type: String,
    /// True when this mention is the entity's first — a node "lighting up".
    pub first_mention: bool,
}

#[derive(Debug, Default)]
pub struct MentionBackfillReport {
    pub memories_scanned: usize,
    pub memories_linked: usize,
    pub mentions_inserted: usize,
    pub descriptions_written: usize,
}

/// The 32-byte `document.id` for a memory. Deterministic per memory id and
/// namespaced by `document.source = "memory:<id>"`, so it can never collide
/// with content-addressed ids from `ingest_document`.
pub fn doc_id_for_memory(memory_id: &str) -> [u8; 32] {
    *blake3::hash(memory_id.as_bytes()).as_bytes()
}

fn open_graph(graph_db: &Path) -> Result<rusqlite::Connection, String> {
    let conn = rusqlite::Connection::open(graph_db).map_err(|e| format!("open graph db: {e}"))?;
    conn.busy_timeout(std::time::Duration::from_secs(5))
        .map_err(|e| format!("busy_timeout: {e}"))?;
    Ok(conn)
}

pub fn load_entity_aliases(conn: &rusqlite::Connection) -> Result<Vec<EntityAlias>, String> {
    let mut stmt = conn
        .prepare("SELECT id, entity_type, canonical FROM entity")
        .map_err(|e| format!("prepare entity load: {e}"))?;
    let rows = stmt
        .query_map([], |r| {
            Ok((
                r.get::<_, Vec<u8>>(0)?,
                r.get::<_, String>(1)?,
                r.get::<_, String>(2)?,
            ))
        })
        .map_err(|e| format!("query entities: {e}"))?;
    let mut out = Vec::new();
    for row in rows.flatten() {
        let (id, entity_type, canonical) = row;
        if canonical.chars().count() < MIN_ALIAS_LEN {
            continue;
        }
        out.push(EntityAlias {
            hex: hex::encode(&id),
            id,
            entity_type,
            canonical,
        });
    }
    Ok(out)
}

/// Find `needle` in `haystack` at word boundaries (both already lowercase).
/// Returns byte span of the first bounded occurrence.
fn find_bounded(haystack: &str, needle: &str) -> Option<(usize, usize)> {
    if needle.is_empty() {
        return None;
    }
    let mut from = 0;
    while let Some(pos) = haystack.get(from..).and_then(|h| h.find(needle)) {
        let start = from + pos;
        let end = start + needle.len();
        let before_ok = haystack
            .get(..start)
            .and_then(|s| s.chars().next_back())
            .is_none_or(|c| !c.is_alphanumeric());
        let after_ok = haystack
            .get(end..)
            .and_then(|s| s.chars().next())
            .is_none_or(|c| !c.is_alphanumeric());
        if before_ok && after_ok {
            return Some((start, end));
        }
        from = end;
    }
    None
}

/// Link one memory's text against the alias set. Writes the `document` row
/// (only when at least one entity matches) and `INSERT OR IGNORE`s a
/// `mention` per matched entity. Returns `(matched alias indices, mentions
/// actually inserted)`.
fn link_text(
    conn: &rusqlite::Connection,
    aliases: &[EntityAlias],
    memory_id: &str,
    text: &str,
) -> Result<(Vec<usize>, usize), String> {
    let lowered = text.to_lowercase();
    let mut matched: Vec<(usize, (usize, usize))> = Vec::new();
    for (i, alias) in aliases.iter().enumerate() {
        if let Some(span) = find_bounded(&lowered, &alias.canonical) {
            matched.push((i, span));
        }
    }
    if matched.is_empty() {
        return Ok((Vec::new(), 0));
    }
    let doc_id = doc_id_for_memory(memory_id);
    let now = chrono::Utc::now().to_rfc3339();
    conn.execute(
        "INSERT INTO document (id, source, ingested_at, visibility)
         VALUES (?1, ?2, ?3, 'private')
         ON CONFLICT(id) DO NOTHING",
        rusqlite::params![doc_id.to_vec(), format!("memory:{memory_id}"), now],
    )
    .map_err(|e| format!("insert document: {e}"))?;
    let mut inserted = 0usize;
    for (i, (start, end)) in &matched {
        let n = conn
            .execute(
                "INSERT OR IGNORE INTO mention
                     (doc_id, entity_id, span_start, span_end, extracted_at)
                 VALUES (?1, ?2, ?3, ?4, ?5)",
                rusqlite::params![
                    doc_id.to_vec(),
                    aliases[*i].id,
                    *start as i64,
                    *end as i64,
                    now
                ],
            )
            .map_err(|e| format!("insert mention: {e}"))?;
        inserted += n;
    }
    Ok((matched.into_iter().map(|(i, _)| i).collect(), inserted))
}

fn attach_memory_db(conn: &rusqlite::Connection, memory_db: &Path) -> Result<(), String> {
    // URI form keeps the attach read-only; rusqlite opens with URI enabled.
    let uri = format!("file:{}?mode=ro", memory_db.display());
    conn.execute("ATTACH DATABASE ?1 AS mem", rusqlite::params![uri])
        .map_err(|e| format!("attach memory db: {e}"))
        .map(|_| ())
}

fn type_label(entity_type: &str) -> String {
    let mut chars = entity_type.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => "Entity".to_string(),
    }
}

fn snippet(content: &str) -> String {
    let clean = content.split_whitespace().collect::<Vec<_>>().join(" ");
    let mut out: String = clean.chars().take(110).collect();
    if clean.chars().count() > 110 {
        out.push('…');
    }
    out
}

/// Write the provenance description for one entity, if its description is
/// empty or previously auto-generated. Requires the memory db attached as
/// `mem`. Returns true when a row was written.
fn refresh_provenance_note(conn: &rusqlite::Connection, entity_id: &[u8]) -> Result<bool, String> {
    let stats: Option<(String, String, i64, Option<String>)> = conn
        .query_row(
            "SELECT e.entity_type, e.canonical, count(*), min(mm.created_at)
             FROM entity e
             JOIN mention mn ON mn.entity_id = e.id
             JOIN document d ON d.id = mn.doc_id
             JOIN mem.memories mm ON mm.id = substr(d.source, 8)
             WHERE e.id = ?1 AND d.source LIKE 'memory:%'
             GROUP BY e.id",
            rusqlite::params![entity_id],
            |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?, r.get(3)?)),
        )
        .map(Some)
        .or_else(|e| match e {
            rusqlite::Error::QueryReturnedNoRows => Ok(None),
            other => Err(format!("provenance stats: {other}")),
        })?;
    let Some((entity_type, _canonical, n, first_at)) = stats else {
        return Ok(false);
    };
    let first_content: Option<String> = conn
        .query_row(
            "SELECT mm.content
             FROM mention mn
             JOIN document d ON d.id = mn.doc_id
             JOIN mem.memories mm ON mm.id = substr(d.source, 8)
             WHERE mn.entity_id = ?1 AND d.source LIKE 'memory:%'
             ORDER BY mm.created_at ASC LIMIT 1",
            rusqlite::params![entity_id],
            |r| r.get(0),
        )
        .ok();
    let since = first_at
        .as_deref()
        .map(|d| d.chars().take(10).collect::<String>())
        .unwrap_or_else(|| "unknown".to_string());
    let memories_word = if n == 1 { "memory" } else { "memories" };
    let mut note = format!(
        "{} {AUTO_NOTE_MARKER} {n} {memories_word} since {since}.",
        type_label(&entity_type)
    );
    if let Some(content) = first_content {
        note.push_str(&format!(" First noted: “{}”", snippet(&content)));
    }
    let changed = conn
        .execute(
            "UPDATE entity SET description = ?2, updated_at = ?3
             WHERE id = ?1
               AND (description IS NULL OR description = ''
                    OR description LIKE '%' || ?4 || '%')
               AND coalesce(description, '') <> ?2",
            rusqlite::params![
                entity_id,
                note,
                chrono::Utc::now().to_rfc3339(),
                AUTO_NOTE_MARKER
            ],
        )
        .map_err(|e| format!("update description: {e}"))?;
    Ok(changed > 0)
}

/// One idempotent pass over every stored memory: link mentions, then write
/// provenance descriptions for every entity that gained links. Safe to run
/// on every boot — re-runs insert nothing new and rewrite identical notes to
/// nothing (`<> ?2` guard).
pub fn backfill_memory_mentions(
    graph_db: &Path,
    memory_db: &Path,
) -> Result<MentionBackfillReport, String> {
    let mut report = MentionBackfillReport::default();
    if !graph_db.exists() || !memory_db.exists() {
        return Ok(report);
    }
    let conn = open_graph(graph_db)?;
    attach_memory_db(&conn, memory_db)?;
    let aliases = load_entity_aliases(&conn)?;
    if aliases.is_empty() {
        return Ok(report);
    }

    let memories: Vec<(String, String)> = {
        let mut stmt = conn
            .prepare(
                "SELECT id, content || coalesce(char(10) || description, '')
                 FROM mem.memories",
            )
            .map_err(|e| format!("prepare memory scan: {e}"))?;
        let rows = stmt
            .query_map([], |r| Ok((r.get(0)?, r.get(1)?)))
            .map_err(|e| format!("scan memories: {e}"))?;
        rows.flatten().collect()
    };

    conn.execute_batch("BEGIN IMMEDIATE")
        .map_err(|e| format!("begin: {e}"))?;
    let mut touched: std::collections::HashSet<usize> = std::collections::HashSet::new();
    for (id, text) in &memories {
        report.memories_scanned += 1;
        let (matched, inserted) = link_text(&conn, &aliases, id, text)?;
        if !matched.is_empty() {
            report.memories_linked += 1;
        }
        report.mentions_inserted += inserted;
        touched.extend(matched);
    }
    for i in touched {
        if refresh_provenance_note(&conn, &aliases[i].id)? {
            report.descriptions_written += 1;
        }
    }
    conn.execute_batch("COMMIT")
        .map_err(|e| format!("commit: {e}"))?;
    Ok(report)
}

/// Real-time path: link one freshly-written memory and refresh the provenance
/// notes of the entities it touched. A missing graph db is a clean no-op
/// (fresh install — the graph never materialized).
pub fn link_new_memory(
    graph_db: &Path,
    memory_db: &Path,
    memory_id: &str,
    text: &str,
) -> Result<Vec<LinkedEntity>, String> {
    if !graph_db.exists() {
        return Ok(Vec::new());
    }
    let conn = open_graph(graph_db)?;
    let aliases = load_entity_aliases(&conn)?;
    if aliases.is_empty() {
        return Ok(Vec::new());
    }
    // Pre-count so "first mention" is knowable after the insert.
    let mut counts: HashMap<usize, i64> = HashMap::new();
    let lowered = text.to_lowercase();
    for (i, alias) in aliases.iter().enumerate() {
        if find_bounded(&lowered, &alias.canonical).is_some() {
            let n: i64 = conn
                .query_row(
                    "SELECT count(*) FROM mention WHERE entity_id = ?1",
                    rusqlite::params![alias.id],
                    |r| r.get(0),
                )
                .map_err(|e| format!("count mentions: {e}"))?;
            counts.insert(i, n);
        }
    }
    let (matched, _) = link_text(&conn, &aliases, memory_id, text)?;
    if matched.is_empty() {
        return Ok(Vec::new());
    }
    if memory_db.exists() {
        attach_memory_db(&conn, memory_db)?;
        for i in &matched {
            let _ = refresh_provenance_note(&conn, &aliases[*i].id);
        }
    }
    Ok(matched
        .into_iter()
        .map(|i| LinkedEntity {
            hex: aliases[i].hex.clone(),
            entity_type: aliases[i].entity_type.clone(),
            first_mention: counts.get(&i).copied().unwrap_or(0) == 0,
        })
        .collect())
}

/// Memory-id → linked entity hexes (bare 64-hex), for a display set of
/// memories. Read-only; used by the brain graph route to draw memory↔entity
/// edges from the mention table.
pub fn mention_links_for_memories(
    graph_db: &Path,
    memory_ids: &[String],
) -> HashMap<String, Vec<String>> {
    let mut out: HashMap<String, Vec<String>> = HashMap::new();
    if memory_ids.is_empty() || !graph_db.exists() {
        return out;
    }
    let Ok(conn) = rusqlite::Connection::open_with_flags(
        graph_db,
        rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY | rusqlite::OpenFlags::SQLITE_OPEN_NO_MUTEX,
    ) else {
        return out;
    };
    let doc_to_memory: HashMap<Vec<u8>, &String> = memory_ids
        .iter()
        .map(|id| (doc_id_for_memory(id).to_vec(), id))
        .collect();
    let placeholders: Vec<String> = (1..=memory_ids.len()).map(|i| format!("?{i}")).collect();
    let sql = format!(
        "SELECT doc_id, entity_id FROM mention WHERE doc_id IN ({})",
        placeholders.join(", ")
    );
    let Ok(mut stmt) = conn.prepare(&sql) else {
        return out;
    };
    let doc_ids: Vec<Vec<u8>> = doc_to_memory.keys().cloned().collect();
    let params: Vec<&dyn rusqlite::types::ToSql> = doc_ids
        .iter()
        .map(|d| d as &dyn rusqlite::types::ToSql)
        .collect();
    if let Ok(rows) = stmt.query_map(params.as_slice(), |r| {
        Ok((r.get::<_, Vec<u8>>(0)?, r.get::<_, Vec<u8>>(1)?))
    }) {
        for (doc_id, entity_id) in rows.flatten() {
            if let Some(mem_id) = doc_to_memory.get(&doc_id) {
                out.entry((*mem_id).clone())
                    .or_default()
                    .push(hex::encode(entity_id));
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn graph_schema(conn: &rusqlite::Connection) {
        conn.execute_batch(
            "CREATE TABLE entity (
                 id BLOB PRIMARY KEY, entity_type TEXT NOT NULL,
                 canonical TEXT NOT NULL, visibility TEXT NOT NULL,
                 created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
                 weight REAL NOT NULL DEFAULT 1.0, description TEXT);
             CREATE TABLE mention (
                 doc_id BLOB NOT NULL, entity_id BLOB NOT NULL,
                 span_start INTEGER NOT NULL, span_end INTEGER NOT NULL,
                 extracted_at TEXT NOT NULL,
                 PRIMARY KEY (doc_id, entity_id));
             CREATE TABLE document (
                 id BLOB PRIMARY KEY, source TEXT NOT NULL,
                 ingested_at TEXT NOT NULL, visibility TEXT NOT NULL);",
        )
        .unwrap();
    }

    fn memory_schema(conn: &rusqlite::Connection) {
        conn.execute_batch(
            "CREATE TABLE memories (
                 id TEXT PRIMARY KEY, key TEXT NOT NULL, content TEXT NOT NULL,
                 description TEXT DEFAULT NULL,
                 created_at TEXT NOT NULL DEFAULT (datetime('now')));",
        )
        .unwrap();
    }

    fn insert_entity(conn: &rusqlite::Connection, entity_type: &str, canonical: &str) -> Vec<u8> {
        let id = blake3::hash(format!("{entity_type}:{canonical}").as_bytes())
            .as_bytes()
            .to_vec();
        conn.execute(
            "INSERT INTO entity (id, entity_type, canonical, visibility, created_at, updated_at)
             VALUES (?1, ?2, ?3, 'private', '2026-01-01', '2026-01-01')",
            rusqlite::params![id, entity_type, canonical],
        )
        .unwrap();
        id
    }

    fn setup() -> (tempfile::TempDir, std::path::PathBuf, std::path::PathBuf) {
        let tmp = tempfile::tempdir().unwrap();
        let graph = tmp.path().join("graph.sqlite");
        let mem = tmp.path().join("memory.db");
        graph_schema(&rusqlite::Connection::open(&graph).unwrap());
        memory_schema(&rusqlite::Connection::open(&mem).unwrap());
        (tmp, graph, mem)
    }

    #[test]
    fn backfill_links_and_describes() {
        let (_tmp, graph, mem) = setup();
        {
            let g = rusqlite::Connection::open(&graph).unwrap();
            insert_entity(&g, "location", "new brunswick");
            insert_entity(&g, "person", "mel schembri");
            let m = rusqlite::Connection::open(&mem).unwrap();
            m.execute(
                "INSERT INTO memories (id, key, content, created_at) VALUES
                 ('m1', 'k1', 'The user moved to New Brunswick last spring.', '2026-05-01 10:00:00'),
                 ('m2', 'k2', 'Met Mel Schembri about GetLadle onboarding.', '2026-06-02 09:00:00'),
                 ('m3', 'k3', 'Unrelated note about groceries.', '2026-06-03 08:00:00')",
                [],
            )
            .unwrap();
        }
        let report = backfill_memory_mentions(&graph, &mem).unwrap();
        assert_eq!(report.memories_scanned, 3);
        assert_eq!(report.memories_linked, 2);
        assert_eq!(report.mentions_inserted, 2);
        assert_eq!(report.descriptions_written, 2);

        let g = rusqlite::Connection::open(&graph).unwrap();
        let desc: String = g
            .query_row(
                "SELECT description FROM entity WHERE canonical = 'new brunswick'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert!(
            desc.starts_with("Location the brain tracks — mentioned in 1 memory since 2026-05-01"),
            "{desc}"
        );
        assert!(desc.contains("New Brunswick"), "{desc}");

        // Idempotent: second run inserts nothing, rewrites nothing.
        let again = backfill_memory_mentions(&graph, &mem).unwrap();
        assert_eq!(again.mentions_inserted, 0);
        assert_eq!(again.descriptions_written, 0);
    }

    #[test]
    fn curated_descriptions_are_never_clobbered() {
        let (_tmp, graph, mem) = setup();
        {
            let g = rusqlite::Connection::open(&graph).unwrap();
            let id = insert_entity(&g, "person", "mel schembri");
            g.execute(
                "UPDATE entity SET description = 'Founder of GetLadle.' WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap();
            let m = rusqlite::Connection::open(&mem).unwrap();
            m.execute(
                "INSERT INTO memories (id, key, content) VALUES ('m1','k1','Call with Mel Schembri')",
                [],
            )
            .unwrap();
        }
        let report = backfill_memory_mentions(&graph, &mem).unwrap();
        assert_eq!(report.mentions_inserted, 1);
        assert_eq!(report.descriptions_written, 0);
        let g = rusqlite::Connection::open(&graph).unwrap();
        let desc: String = g
            .query_row("SELECT description FROM entity", [], |r| r.get(0))
            .unwrap();
        assert_eq!(desc, "Founder of GetLadle.");
    }

    #[test]
    fn word_boundaries_prevent_substring_hits() {
        assert!(find_bounded("i love melon bread", "mel").is_none());
        assert!(find_bounded("talk to mel today", "mel").is_some());
        assert!(find_bounded("new brunswick, canada", "new brunswick").is_some());
        assert!(find_bounded("newer brunswick-ish", "new brunswick").is_none());
    }

    #[test]
    fn link_new_memory_reports_first_mention_and_links() {
        let (_tmp, graph, mem) = setup();
        {
            let g = rusqlite::Connection::open(&graph).unwrap();
            insert_entity(&g, "person", "mel schembri");
            let m = rusqlite::Connection::open(&mem).unwrap();
            m.execute(
                "INSERT INTO memories (id, key, content) VALUES ('m9','k9','Mel Schembri demo feedback')",
                [],
            )
            .unwrap();
        }
        let linked = link_new_memory(&graph, &mem, "m9", "Mel Schembri demo feedback").unwrap();
        assert_eq!(linked.len(), 1);
        assert!(linked[0].first_mention);
        assert_eq!(linked[0].entity_type, "person");

        // Second memory: no longer a first mention.
        let linked2 = link_new_memory(&graph, &mem, "m10", "Mel Schembri again").unwrap();
        assert!(!linked2[0].first_mention);

        // The route-side lookup sees the link.
        let map = mention_links_for_memories(&graph, &["m9".to_string()]);
        assert_eq!(map.get("m9").map(|v| v.len()), Some(1));
    }
}
