#!/bin/bash
# Stamp the iOS build number (and optionally the marketing version) into
# ios/PermagentMobile/project.yml, then regenerate the Xcode project.
#
# Why a script rather than "just edit it in Xcode": the .xcodeproj AND
# Info.plist are both generated by xcodegen from project.yml, so anything
# Xcode's General tab writes survives exactly until the next `xcodegen
# generate` and then vanishes. project.yml is the only durable place.
#
# The build number comes from the git commit count. It is monotonic, needs no
# bookkeeping, and cannot collide — which matters because App Store Connect
# rejects a re-used (version, build) pair outright.
#
#   scripts/ios_build_number.sh              # bump build number only
#   scripts/ios_build_number.sh 1.32.0       # also set the marketing version
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
YML="$ROOT/ios/PermagentMobile/project.yml"
MARKETING="${1:-}"

[ -f "$YML" ] || { echo "ERROR: $YML not found" >&2; exit 1; }

BUILD="$(git -C "$ROOT" rev-list --count HEAD)"

CURRENT="$(grep -E '^\s*CURRENT_PROJECT_VERSION:' "$YML" | head -1 | sed 's/.*: *//')"
# Going BACKWARDS is fatal — App Store Connect rejects a re-used or lower
# build number. Standing still is not: re-running with no new commits just
# re-applies project.yml, which is how the initial wiring gets picked up.
if [ -n "$CURRENT" ] && [ "$BUILD" -lt "$CURRENT" ]; then
  echo "ERROR: commit count ($BUILD) is BELOW the current build number ($CURRENT)." >&2
  echo "       That would be rejected on upload. Check you are on the right branch." >&2
  exit 1
fi
if [ "$BUILD" = "$CURRENT" ]; then
  echo "  build number unchanged ($BUILD) — no new commits; re-applying project.yml"
fi

YML="$YML" BUILD="$BUILD" MARKETING="$MARKETING" python3 <<'PYEOF'
import os, re
path = os.environ["YML"]
src = open(path).read()

build = os.environ["BUILD"]
new, n = re.subn(r"^(\s*CURRENT_PROJECT_VERSION:\s*).*$",
                 lambda m: m.group(1) + build, src, count=1, flags=re.M)
if n != 1:
    raise SystemExit("could not find CURRENT_PROJECT_VERSION in project.yml")

marketing = os.environ.get("MARKETING") or ""
if marketing:
    if not re.fullmatch(r"\d+\.\d+(\.\d+)?", marketing):
        raise SystemExit(f"marketing version {marketing!r} must look like 1.32 or 1.32.0")
    new, n = re.subn(r'^(\s*MARKETING_VERSION:\s*).*$',
                     lambda m: m.group(1) + f'"{marketing}"', new, count=1, flags=re.M)
    if n != 1:
        raise SystemExit("could not find MARKETING_VERSION in project.yml")

open(path, "w").write(new)
print(f"  CURRENT_PROJECT_VERSION -> {build}")
if marketing:
    print(f"  MARKETING_VERSION       -> {marketing}")
PYEOF

cd "$ROOT/ios/PermagentMobile"
xcodegen generate > /dev/null
echo "  xcodeproj regenerated"

# Prove it landed where it actually matters: the two build settings are inert
# unless Info.plist references them, which is the bug this whole thing fixes.
grep -q 'CFBundleShortVersionString: "\$(MARKETING_VERSION)"' project.yml \
  && grep -q 'CFBundleVersion: "\$(CURRENT_PROJECT_VERSION)"' project.yml \
  || { echo "ERROR: Info.plist no longer references the version build settings —" >&2
       echo "       literal values there make every build ship as 1.0 (1)." >&2; exit 1; }
echo "Done."
