#!/bin/bash
# Bundle a self-contained Node runtime + the web-search MCP server packages
# (Brave, Tavily) into the Tauri app so search works in the shipped .app, which
# has no system Node/npx on PATH (#358).
#
# Layout produced under src-tauri/resources/mcp-runtime/ (→ bundled at
# Contents/Resources/mcp-runtime/):
#   node                         the Node binary for the build arch
#   node_modules/...             the pre-installed server packages
#
# The daemon launches each server by invoking the bundled node directly against
# the package's entry JS (see ui/command-center/src/lib/searchProviders.ts) — no
# npx (so no runtime registry fetch) and no #!/usr/bin/env node shebang (so no
# dependency on Node being on the daemon's PATH).
set -euo pipefail

# --- Pins (bump deliberately) ---
NODE_VERSION="22.22.1"
# #377: the @modelcontextprotocol package is npm-deprecated; the official
# Brave-maintained server replaces it.
BRAVE_PKG="@brave/brave-search-mcp-server@2.0.85"
TAVILY_PKG="tavily-mcp@0.2.20"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TAURI_DIR="$SCRIPT_DIR/../src-tauri"
OUT="$TAURI_DIR/resources/mcp-runtime"

ARCH="$(uname -m)"
case "$ARCH" in
  arm64)  NODE_ARCH="darwin-arm64" ;;
  x86_64) NODE_ARCH="darwin-x64" ;;
  *)      echo "ERROR: unsupported arch $ARCH" >&2; exit 1 ;;
esac

mkdir -p "$OUT"

# --- 1. Stage the Node binary ---
if [ -x "$OUT/node" ] && [ "$("$OUT/node" --version 2>/dev/null || true)" = "v$NODE_VERSION" ]; then
  echo "Node v$NODE_VERSION already staged: $OUT/node"
else
  TARBALL="node-v${NODE_VERSION}-${NODE_ARCH}.tar.gz"
  URL="https://nodejs.org/dist/v${NODE_VERSION}/${TARBALL}"
  TMP="$(mktemp -d)"
  echo "Downloading $URL"
  curl -fsSL "$URL" -o "$TMP/$TARBALL"
  tar -xzf "$TMP/$TARBALL" -C "$TMP"
  cp "$TMP/node-v${NODE_VERSION}-${NODE_ARCH}/bin/node" "$OUT/node"
  chmod +x "$OUT/node"
  rm -rf "$TMP"
  echo "Node staged: $OUT/node ($("$OUT/node" --version))"
fi

# --- 2. Pre-install the MCP server packages (production deps only) ---
# Reinstalled each build so the pin is authoritative. node_modules is staged
# flat next to the binary; entry points are resolved by the frontend.
rm -rf "$OUT/node_modules" "$OUT/package.json" "$OUT/package-lock.json"
cat > "$OUT/package.json" <<EOF
{
  "name": "permagent-mcp-runtime",
  "private": true,
  "description": "Bundled web-search MCP servers (#358). Do not edit by hand — regenerated by copy-mcp-runtime.sh.",
  "dependencies": {
    "@brave/brave-search-mcp-server": "${BRAVE_PKG##*@}",
    "tavily-mcp": "${TAVILY_PKG##*@}"
  }
}
EOF

echo "Installing $BRAVE_PKG, $TAVILY_PKG"
npm install --prefix "$OUT" --omit=dev --no-audit --no-fund --silent \
  "$BRAVE_PKG" "$TAVILY_PKG"

# --- 3. Sanity: entry points exist ---
for entry in \
  "node_modules/@brave/brave-search-mcp-server/dist/index.js" \
  "node_modules/tavily-mcp/build/index.js"; do
  [ -f "$OUT/$entry" ] || { echo "ERROR: expected entry missing: $OUT/$entry" >&2; exit 1; }
done

echo "MCP runtime staged at $OUT ($(du -sh "$OUT" | cut -f1))"
